CREATE TABLE CYTATY AS SELECT * FROM ZTPD.CYTATY;

SELECT * FROM CYTATY
WHERE UPPER(TEKST)LIKE '%OPTYMISTA%' AND UPPER(TEKST) LIKE '%PESYMISTA%';

CREATE INDEX CYTATY_CTX_IDX ON CYTATY(TEKST) INDEXTYPE IS CTXSYS.CONTEXT;

SELECT * FROM CYTATY WHERE CONTAINS(TEKST, 'optymista AND pesymista', 1) > 0;

SELECT * FROM CYTATY WHERE CONTAINS(TEKST, 'pesymista NOT optymista', 1) > 0;

SELECT * FROM CYTATY WHERE CONTAINS(TEKST, 'NEAR((pesymista, optymista), 3)', 1) > 0;
SELECT * FROM CYTATY WHERE CONTAINS(TEKST, 'NEAR((pesymista, optymista), 10)', 1) > 0;

SELECT * FROM CYTATY WHERE CONTAINS(TEKST, 'życi%', 1) > 0;
SELECT TEKST, SCORE(1) FROM CYTATY WHERE CONTAINS(TEKST, 'życi%', 1) > 0;
SELECT TEKST, SCORE(1) FROM CYTATY WHERE CONTAINS(TEKST, 'życi%', 1) > 0 ORDER BY SCORE(1) DESC FETCH FIRST 1 ROW ONLY;

SELECT * FROM CYTATY WHERE CONTAINS(TEKST, 'FUZZY(PROBELM)', 1) > 0;

INSERT INTO CYTATY VALUES (3000,
'Bertrand Russell',
'To smutne, że głupcy są tacy pewni
siebie, a ludzie rozsądni tacy pełni wątpliwości.'
);
SELECT * FROM CYTATY WHERE CONTAINS(TEKST, 'głupcy', 1) > 0;

select *
from DR$CYTATY_CTX_IDX$I WHERE TOKEN_TEXT = 'GŁUPCY';
drop index CYTATY_CTX_IDX;

CREATE INDEX CYTATY_CTX_IDX ON CYTATY(TEKST) INDEXTYPE IS CTXSYS.CONTEXT;

SELECT * FROM CYTATY WHERE CONTAINS(TEKST, 'głupcy', 1) > 0;
drop index CYTATY_CTX_IDX;

drop table CYTATY;

--Zaawansowane indeksowanie i wyszukiwanie

CREATE TABLE QUOTES AS SELECT * FROM ZTPD.QUOTES;
CREATE INDEX QUOTES_CTX_IDX ON QUOTES(TEXT) INDEXTYPE IS CTXSYS.CONTEXT;

SELECT * FROM QUOTES WHERE CONTAINS(TEXT, 'work', 1) > 0;
SELECT * FROM QUOTES WHERE CONTAINS(TEXT, '$work', 1) > 0;
SELECT * FROM QUOTES WHERE CONTAINS(TEXT, 'working', 1) > 0;
SELECT * FROM QUOTES WHERE CONTAINS(TEXT, '$working', 1) > 0;

select AUTHOR, TEXT
from QUOTES
where CONTAINS(TEXT, 'it', 1) > 0;

SELECT * FROM CTX_STOPLISTS;
-- DEFAULT_STOPLIST
SELECT * FROM CTX_STOPWORDS;

DROP INDEX QUOTES_CTX_IDX;

CREATE INDEX QUOTES_CTX_IDX ON QUOTES(TEXT) INDEXTYPE IS CTXSYS.CONTEXT PARAMETERS('STOPLIST CTXSYS.EMPTY_STOPLIST');

SELECT * FROM QUOTES WHERE CONTAINS(TEXT, 'it', 1) > 0;

SELECT * FROM QUOTES WHERE CONTAINS(TEXT, 'fool AND humans', 1) > 0;
SELECT * FROM QUOTES WHERE CONTAINS(TEXT, 'fool AND computer', 1) > 0;

SELECT * FROM QUOTES WHERE CONTAINS(TEXT, '(fool AND humans) within SENTENCE', 1) > 0;
-- sekcja SENTENCE nie istnieje

DROP INDEX QUOTES_CTX_IDX;

begin
    ctx_ddl.create_section_group('nullgroup', 'NULL_SECTION_GROUP');
    ctx_ddl.add_special_section('nullgroup', 'SENTENCE');
    ctx_ddl.add_special_section('nullgroup', 'PARAGRAPH');
end;

CREATE INDEX QUOTES_CTX_IDX ON QUOTES(TEXT) INDEXTYPE IS CTXSYS.CONTEXT PARAMETERS('SECTION GROUP nullgroup');
SELECT * FROM QUOTES WHERE CONTAINS(TEXT, '(fool AND humans) within SENTENCE', 1) > 0;
SELECT * FROM QUOTES WHERE CONTAINS(TEXT, '(fool AND computer) within SENTENCE', 1) > 0;

SELECT * FROM QUOTES WHERE CONTAINS(TEXT, 'humans', 1) > 0;

DROP INDEX QUOTES_CTX_IDX;

begin
    ctx_ddl.create_preference('my_lexer','BASIC_LEXER');
    ctx_ddl.set_attribute('my_lexer', 'printjoins', '_-');
    ctx_ddl.set_attribute ('my_lexer', 'index_text', 'YES');
end;

CREATE INDEX QUOTES_CTX_IDX ON QUOTES(TEXT) INDEXTYPE IS CTXSYS.CONTEXT PARAMETERS('LEXER my_lexer');

SELECT * FROM QUOTES WHERE CONTAINS(TEXT, 'humans', 1) > 0;
SELECT * FROM QUOTES WHERE CONTAINS(TEXT, 'non\-humans', 1) > 0;

DROP INDEX QUOTES_CTX_IDX;
DROP TABLE QUOTES;
begin
    ctx_ddl.drop_preference('my_lexer');
end;