CREATE TABLE MOVIES_COPY AS SELECT * FROM ZTPD.MOVIES;

SELECT * FROM MOVIES_COPY;

select *
from MOVIES_COPY
where COVER is null;

SELECT TITLE, LENGTH(COVER)
FROM MOVIES_COPY WHERE COVER IS NOT NULL;


SELECT TITLE, LENGTH(COVER)
FROM MOVIES_COPY WHERE COVER IS NULL;

SELECT * FROM ALL_DIRECTORIES;

UPDATE MOVIES_COPY
SET COVER = EMPTY_BLOB(), MIME_TYPE = 'image/jpeg'
WHERE ID = 66;
COMMIT;

SELECT TITLE, LENGTH(COVER)
FROM MOVIES_COPY WHERE ID = 65 OR ID = 66;
--


DECLARE
  v_bfile BFILE;
  v_blob BLOB;
  v_size NUMBER;
BEGIN
    v_bfile := BFILENAME('TPD_DIR', 'escape.jpg');
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);
    v_size := DBMS_LOB.GETLENGTH(v_bfile);
    
    SELECT COVER INTO v_blob FROM MOVIES_COPY WHERE ID = 66 FOR UPDATE;
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, v_size);
    DBMS_LOB.CLOSE(v_bfile);
    COMMIT;
END;

CREATE TABLE TEMP_COVERS (
    movie_id NUMBER(12),
    image BFILE,
    mime_type VARCHAR2(50)
);

INSERT INTO TEMP_COVERS
VALUES (
    65, BFILENAME('TPD_DIR', 'eagles.jpg'), 'image/jpeg'
);
commit;

SELECT movie_id, DBMS_LOB.GETLENGTH(image) FROM TEMP_COVERS;

DECLARE
    v_mime VARCHAR(50);
    v_bfile BFILE;
    v_blob BLOB;
    v_size NUMBER;
BEGIN
    SELECT image, mime_type INTO v_bfile, v_mime FROM TEMP_COVERS WHERE MOVIE_ID = 65;
    DBMS_LOB.OPEN(v_bfile, DBMS_LOB.LOB_READONLY);    
    v_size := DBMS_LOB.GETLENGTH(v_bfile);
    DBMS_LOB.CREATETEMPORARY(v_blob, TRUE);
    DBMS_LOB.LOADFROMFILE(v_blob, v_bfile, v_size);
    UPDATE MOVIES_COPY SET COVER = v_blob, MIME_TYPE = v_mime WHERE ID = 65;
    DBMS_LOB.CLOSE(v_bfile);
    DBMS_LOB.FREETEMPORARY(v_blob);
    COMMIT;
END;

SELECT ID, DBMS_LOB.GETLENGTH(COVER) FROM MOVIES_COPY WHERE ID = 65 OR ID = 66;

DROP TABLE TEMP_COVERS;




