INSERT INTO USER_SDO_GEOM_METADATA
VALUES('FIGURY',
       'KSZTALT',
       MDSYS.SDO_DIM_ARRAY(
               MDSYS.SDO_DIM_ELEMENT('X', 0, 9, 0.01),
               MDSYS.SDO_DIM_ELEMENT('Y', 0, 9, 0.01)),
       NULL);

SELECT SDO_TUNE.ESTIMATE_RTREE_INDEX_SIZE(3000000, 8192, 10, 2, 0) FROM DUAL;

CREATE INDEX figury_spatial_idx ON figury(ksztalt) INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

-- zastosowano tutaj tylko indeks, który przybliża kształty do prostoków. Zwrócono wyłacznie kandydatow 
SELECT id FROM figury WHERE SDO_FILTER(ksztalt, MDSYS.SDO_GEOMETRY(2001, NULL, MDSYS.SDO_POINT_TYPE(3,3,null), null, null)) = 'TRUE';

-- Kandydatow nastepnie przefiltrowano by zwrocic faktyczny wynik
SELECT id FROM figury WHERE SDO_RELATE(ksztalt, MDSYS.SDO_GEOMETRY(2001, NULL, MDSYS.SDO_POINT_TYPE(3,3,null), null, null), 'mask=anyinteract') = 'TRUE';

SELECT CITY_NAME, ROUND(SDO_NN_DISTANCE(1),7) ODL
FROM MAJOR_CITIES
WHERE SDO_NN(GEOM, (SELECT GEOM FROM MAJOR_CITIES WHERE city_name='Warsaw'), 'sdo_num_res=10 unit=km',1) = 'TRUE'
  AND ID <> (SELECT ID FROM MAJOR_CITIES where city_name='Warsaw')
ORDER BY ODL;

SELECT CITY_NAME, CNTRY_NAME
FROM MAJOR_CITIES
WHERE SDO_RELATE(GEOM, (SELECT GEOM FROM COUNTRY_BOUNDARIES WHERE CNTRY_NAME='Slovakia'), 'mask=inside+contains') = 'TRUE';

-- = 'FALSE' nie działa?
SELECT CB2.CNTRY_NAME, SDO_GEOM.SDO_DISTANCE(CB1.GEOM, CB2.GEOM, 1, 'unit=km')
FROM COUNTRY_BOUNDARIES CB1, COUNTRY_BOUNDARIES CB2
WHERE CB1.CNTRY_NAME = 'Poland' AND SDO_GEOM.SDO_DISTANCE(CB1.GEOM, CB2.GEOM, 1, 'unit=km') > 0;

SELECT CB1.CNTRY_NAME PANSTWO, SDO_GEOM.SDO_LENGTH(SDO_GEOM.SDO_INTERSECTION(CB1.GEOM, CB2.GEOM, 1), 1, 'unit=km') ODL
FROM COUNTRY_BOUNDARIES CB1 ,COUNTRY_BOUNDARIES CB2
WHERE SDO_RELATE(CB1.GEOM, CB2.GEOM, 'mask=touch') = 'TRUE' AND CB2.CNTRY_NAME='Poland';

SELECT CNTRY_NAME, SDO_GEOM.SDO_AREA(GEOM)
FROM COUNTRY_BOUNDARIES
where SDO_GEOM.SDO_AREA(GEOM) = (SELECT MAX(SDO_GEOM.SDO_AREA(GEOM)) FROM COUNTRY_BOUNDARIES);

SELECT SDO_GEOM.SDO_AREA(SDO_GEOM.SDO_MBR(SDO_GEOM.SDO_UNION(CB1.GEOM, CB2.GEOM, 0.01)),1, 'unit=SQ_KM')
FROM MAJOR_CITIES CB1, MAJOR_CITIES CB2
WHERE CB1.CITY_NAME = 'Warsaw' AND CB2.CITY_NAME='Lodz';

SELECT SDO_GEOM.SDO_UNION(A.GEOM, B.GEOM, 0.01).GET_DIMS() ||
       SDO_GEOM.SDO_UNION(A.GEOM, B.GEOM, 0.01).GET_LRS_DIM() ||
       LPAD(SDO_GEOM.SDO_UNION(A.GEOM, B.GEOM, 0.01).GET_GTYPE(), 2, '0') GTYPE
FROM COUNTRY_BOUNDARIES A, MAJOR_CITIES B
WHERE A.CNTRY_NAME = 'Poland'AND B.CITY_NAME = 'Prague';

SELECT MC.CITY_NAME MIASTO, SDO_GEOM.SDO_DISTANCE(MC.GEOM, SDO_GEOM.SDO_CENTROID(CB.GEOM, 0.01), 1, 'unit=km') ODL
FROM MAJOR_CITIES MC, COUNTRY_BOUNDARIES CB
ORDER BY ODL;

SELECT R.NAME, SUM(SDO_GEOM.SDO_LENGTH(SDO_GEOM.SDO_INTERSECTION(R.GEOM, CB.GEOM, 1), 1, 'unit=km')) dl
FROM RIVERS R, COUNTRY_BOUNDARIES CB
WHERE SDO_RELATE(R.GEOM, CB.GEOM, 'mask=anyinteract') = 'TRUE'
AND CB.CNTRY_NAME = 'Poland'
GROUP BY R.NAME;
