select lpad('-',2*(level-1),'|-') || t.owner||'.'||t.type_name||' (FINAL:'||t.final||
', INSTANTIABLE:'||t.instantiable||', ATTRIBUTES:'||t.attributes||', METHODS:'||t.methods||')'
from all_types t
start with t.type_name = 'ST_GEOMETRY'
connect by prior t.type_name = t.supertype_name
 and prior t.owner = t.owner;

select distinct m.method_name
from all_type_methods m
where m.type_name like 'ST_POLYGON' and m.owner = 'MDSYS'
order by 1;

create table MYST_MAJOR_CITIES (
    FIPS_CNTRY VARCHAR2(2),
    CITY_NAME VARCHAR2(40),
    STGEOM ST_POINT
);

insert into MYST_MAJOR_CITIES (FIPS_CNTRY, CITY_NAME, STGEOM)
select ztpd.FIPS_CNTRY, ztpd.CITY_NAME, TREAT(ST_POINT.FROM_SDO_GEOM(ztpd.GEOM) AS ST_POINT) STGEOM
from MAJOR_CITIES ztpd;

insert into MYST_MAJOR_CITIES (FIPS_CNTRY, CITY_NAME, STGEOM)
values ('PL', 'Szczyrk', ST_POINT(19.036107, 49.718655, 8307));

create table MYST_COUNTRY_BOUNDARIES (
    FIPS_CNTRY VARCHAR2(2),
    CNTRY_NAME VARCHAR2(40),
    STGEOM ST_MULTIPOLYGON
);
insert into MYST_COUNTRY_BOUNDARIES (FIPS_CNTRY, CNTRY_NAME, STGEOM)
select ztpd.FIPS_CNTRY, ztpd.CNTRY_NAME, ST_MULTIPOLYGON(ztpd.GEOM)
from COUNTRY_BOUNDARIES ztpd;

select t.STGEOM.ST_GEOMETRYTYPE(), count(*) from MYST_COUNTRY_BOUNDARIES t
group by t.STGEOM.ST_GEOMETRYTYPE();

select t.STGEOM.ST_ISSIMPLE()
from MYST_COUNTRY_BOUNDARIES t;

SELECT MCB.CNTRY_NAME, COUNT(*)
FROM MYST_MAJOR_CITIES MMC, MYST_COUNTRY_BOUNDARIES MCB
WHERE MCB.STGEOM.ST_CONTAINS(MMC.STGEOM) = 1
GROUP BY MCB.CNTRY_NAME;

SELECT M2.CNTRY_NAME
FROM MYST_COUNTRY_BOUNDARIES M1, MYST_COUNTRY_BOUNDARIES M2
WHERE M1.STGEOM.ST_TOUCH(M2.STGEOM) = 1 AND M1.CNTRY_NAME = 'Czech Republic'

SELECT DISTINCT R.NAME
FROM MYST_COUNTRY_BOUNDARIES M, RIVERS R
WHERE M.STGEOM.ST_INTERSECTS(ST_LINESTRING(R.GEOM)) = 1 AND M.CNTRY_NAME = 'Czech Republic'

SELECT TREAT(M1.STGEOM.ST_UNION(M2.STGEOM) as ST_POLYGON).ST_AREA()
FROM MYST_COUNTRY_BOUNDARIES M1, MYST_COUNTRY_BOUNDARIES M2
WHERE M1.CNTRY_NAME = 'Czech Republic' AND M2.CNTRY_NAME = 'Slovakia'

SELECT A.STGEOM.ST_DIFFERENCE(ST_GEOMETRY(B.GEOM)).ST_GEOMETRYTYPE()
FROM MYST_COUNTRY_BOUNDARIES A, WATER_BODIES B
WHERE A.CNTRY_NAME = 'Hungary'
AND B.NAME = 'Balaton';

select B.CNTRY_NAME A_NAME, COUNT(*) from MYST_COUNTRY_BOUNDARIES B, MYST_MAJOR_CITIES C
WHERE SDO_WITHIN_DISTANCE(C.STGEOM, B.STGEOM, 'distance=100 unit=km') = 'TRUE' and B.CNTRY_NAME = 'Poland'
group by B.CNTRY_NAME;

INSERT INTO USER_SDO_GEOM_METADATA
SELECT 'MYST_MAJOR_CITIES', 'STGEOM', T.DIMINFO, T.SRID
FROM ALL_SDO_GEOM_METADATA T
WHERE T.TABLE_NAME = 'MAJOR_CITIES';

CREATE INDEX MYST_MAJOR_CITIES_IDX ON MYST_MAJOR_CITIES(STGEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

EXPLAIN PLAN FOR
select B.CNTRY_NAME A_NAME, COUNT(*) from MYST_COUNTRY_BOUNDARIES B, MYST_MAJOR_CITIES C
WHERE SDO_WITHIN_DISTANCE(C.STGEOM, B.STGEOM, 'distance=100 unit=km') = 'TRUE' and B.CNTRY_NAME = 'Poland'
group by B.CNTRY_NAME;

SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY);
