(:for $k in doc('file:////F://programowanie//studia//magisterka//sem2//z_technologie_przetwarzania_danych//XPath-XSLT//swiat.xml'):)
(:/SWIAT/KRAJE/KRAJ[starts-with(NAZWA, 'A')]:)
(:/SWIAT/KRAJE/KRAJ[substring(NAZWA, 1,1)=substring(STOLICA, 1,1)]:)
doc('file:////F://programowanie//studia//magisterka//sem2//z_technologie_przetwarzania_danych//XPath-XSLT//zesp_prac.xml')
(:/ZESPOLY/ROW/PRACOWNICY/ROW/NAZWISKO:)
(:/ZESPOLY/ROW[NAZWA='SYSTEMY EKSPERCKIE']/PRACOWNICY/ROW/NAZWISKO:)
(:/count(/ZESPOLY/ROW[ID_ZESP=10]/PRACOWNICY/ROW):)
(:/ZESPOLY/ROW/PRACOWNICY/ROW[ID_SZEFA=100]/NAZWISKO:)
/sum(/ZESPOLY/ROW[PRACOWNICY/ROW/NAZWISKO='BRZEZINSKI']/PRACOWNICY/ROW/PLACA_POD)
